[package]
name = "thermal-camera"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
eframe = "0.22.0"
image = "0.24.6"
lazy_static = "1.4.0"
rppal = "0.14.1"
structopt = "0.3.26"
sys-mount = "2.1.0"
